### ISSUE TITLE
Toggling feature?

### ISSUE THREAD

**Issue by Swigglezz** [MrIvanPlays/AnnouncementsEverywhere#2]
**Is your feature request related to a problem? Please describe.**
N/A
**Describe the solution you'd like**
Could you add a command where when a player types /announcements on/off it turns the announcements on and off for them in chat?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MrIvanPlays** [comment]
Can be done from the config and then /aereload. Sorry for late response.
