### ISSUE TITLE
Hoverable/Clickable text for books

### ISSUE THREAD

**Issue by ColaIan** [MrIvanPlays/AnnouncementsEverywhere#3]
**Describe the solution you'd like**
I'd like to have hoverable and/or clickable text for books (Maybe json or custom syntax for clickable text)

**Describe alternatives you've considered**
NIL

**Additional context**
Had been asking since 11 August, 2019 in Discord PM 👀.

**Comment by MrIvanPlays** [comment]
Implemented in version 4.0.1
